### ISSUE TITLE
您好，models名称报错了

### ISSUE THREAD

**Issue by upupbo** [Jiangfeng-Xiong/satellite_seg#5]
cb@ceo-pc:~/code/satellite_seg$ sh run_train.sh
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/home/cb/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cb/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1308, in <module>
    download_scripts_and_run()
  File "/home/cb/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1304, in download_scripts_and_run
    main()
  File "/home/cb/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1299, in main
    print_func=print_func, user_credential=user_credential)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 1219, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/cb/anaconda3/lib/python3.6/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
WARNING:root:Setting up a new session...
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    train(args)
  File "train.py", line 111, in train
    model = get_model(args.arch, n_classes)
  File "/home/cb/code/satellite_seg/models/__init__.py", line 26, in get_model
    fmodel = get_instance(name)
  File "/home/cb/code/satellite_seg/models/__init__.py", line 23, in get_instance
    }[name]
KeyError: 'pspnet-densenet-s1s2-crf2'

**Comment by Jiangfeng-Xiong** [comment]
[init文件](https://github.com/Jiangfeng-Xiong/satellite_seg/blob/master/models/__init__.py)的问题，已更新, 可以替换下这个文件
